### ISSUE TITLE
Some wrong tiles in a map

### ISSUE THREAD

**Issue by moufmouf** [nolway/wa-map-optimizer#2]
In the map here:

https://github.com/buenni86/tag-der-vernetzung

(accessible here: https://play.workadventu.re/@/db-systel/db/tag-der-vernetzung)

there is a problem after optimization it seems.
Look at the lake in the middle of the map. You'll see 2 sand tiles in the left of the lake (where you should see water tiles instead)

**Comment by nolway** [comment]
Fixed =)
