### ISSUE TITLE
Animations broken

### ISSUE THREAD

**Issue by danez** [nolway/wa-map-optimizer#4]
https://github.com/nolway/wa-map-optimizer/commit/ecb1d8de14368f28cf8098316b583bd42f1bc37e broke rendering of animations for me. Removing this code makes it work again.

Looking at the generated pngs I see that the first tile from the animation (the one with tileid === 0) is completely missing in the png file.

Do you have any idea what could be the issue? I'm happy to send a PR, but have no idea what actually is going on. :)

https://user-images.githubusercontent.com/231804/233518684-b032ca36-c5d3-4861-a3b5-8bbc505d87db.mp4

**Comment by nolway** [comment]
Fixed =)
